# Site settings
title: NullRecurrent
subtitle: [ 虚无空间]
keywords: NullRecurrent
description: 莫学韩卢逐块，直须狮子咬人。
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.wikileaks.org/" # 你的域名
page_no_title: "NullRecurrent's blog" # 文章无标题时默认显示内容
beian: # "备案号"
author: 零常返
email: NullRecurrent@gmail.com

# Build settings
permalink: /:year/:month/:day/:title/
exclude: ["README.md", "changelog.md", "server", "tools", "Pipfile"]
plugins:
  - jekyll-paginate
  - jemoji


# always get github's error email saying redcarpet is not supported,
# so change it to kramdown.
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM


# Pageinate settings
paginate: 8 # 分页大小
paginate_path: "page/:num/"

# Search settings
baidu_search: #true
google_search:  true

# Menu settings
menu:
  - page: 首页
    directory: .
    icon: icon-home
  - page: 归档
    directory: archives/
    icon: icon-archive
  - page: 标签
    directory: tags/
    icon: icon-tags
  - page: 留言
    directory: guestbook/
    icon: icon-guestbook
  - page: 关于
    directory: about/
    icon: icon-about
#  - page: 订阅
#    directory: feed.xml
#    icon: icon-rss

# Link settings
links: # 友情链接

  - title: (本主页源自) oukohou's github page 
    url: https://github.com/oukohou/oukohou.github.io
#  - title:
#    url: http://jekyllcn.com/
 


# Google Analytics
ga_track_id: 'UA-130856615-1'            # Format: UA-xxxxxx-xx
ga_domain: www.oukohou.wang              # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto


# Code hub settings
#codehub: # 代仓库
 # - title: Github
  #  url: https://github.com/oukohou


 
